removing old branch reference and stating clean
labforward/platform-gha pull request #10
Opened 2023-01-23 14:41 UTC by gabrielmathias

Removing a previous branch has been used a lot to solve errors in the apps, so I propose performing this as a standard step on the build and deploy action.

2023-01-26 19:37 UTC, gilvan-fernandes requested changes

2023-01-26 19:37 UTC, gilvan-fernandes commented on platform/delivery/action.yml
>          gh_pat: ${{ inputs.gh_pat }}
We'll need to increase the version in line 62 for the release. 1.1.0

2023-02-01 12:25 UTC, gabrielmathias commented on platform/branch/create/action.yml
> +        [ '${{ inputs.reuse_branch }}' = 'true' ] && echo "reusing branch" || git push origin --delete ${{ inputs.platform_branch }} && echo "old branch deleted" || echo "no existing old branch to de
next commit solved it.

2023-02-01 13:59 UTC, gilvan-fernandes approved these changes

2023-02-03 01:17 UTC, gilvan-fernandes approved these changes

2023-02-03 01:18 UTC, merged